from django.apps import AppConfig


# this is include since Django 1.7 but is autogenerated in Django 1.9
# this file allows for one to configure the app config
class PetsConfig(AppConfig):
    name = 'pets'
